export const vueDevRoutes = [
	{
	    path:'/',
	    name:'index',
	    component:()=>import('@/pages/index/index.vue')
	},
	{
	    path:'/product/detail',
	    name:'productDetail',
	    component:()=>import('@/pages/product/detail.vue')
	},
	{
	    path:'/pages/cart',
	    name:'cart',
	    component:()=>import('@/pages/cart/cart.vue')
	},
    {
        path:'/pages/user',
        name:'user',
        component:()=>import('@/pages/user/user.vue'),
        beforeEnter:(to,from,next)=>{
            console.log(to);
            console.log(from)
            next();
        },
        children:[
            {
                path:'/pages/user/order',
                name:'order',
                component:()=>import('@/pages/user/order/order.vue'),
            },
			{
			    path:'/pages/user/address',
			    name:'address',
			    component:()=>import('@/pages/user/address/address.vue'),
			}
        ]
    }
]